### ISSUE TITLE
Using with Foundation... thoughts?

### ISSUE THREAD

**Issue by dlewand691** [StudioThick/megatype#22]
I use Zurb's Foundation framework... any thoughts on the best way to integrate Megatype? Thanks for such a great tool!

**Comment by tbredin** [comment]
Hey there,
We've experimented with Foundation 6 and MegaType, and because Foundation is built in `rem` units by default, the two integrate really well. 

For your overrides, I'd recommend adding separate settings files for each of Foundation and MegaType, duplicated from `_settings.scss` (in Foundation) and `_config.scss` (in MegaType). One thing I added was to pull breakpoints for MegaType's `$breakpoint-map` right from Foundation, which looks like this:

``` scss
// _config.scss
// map for flexible retrieval of breakpoint info
$breakpoint-map: (
    0: (
        start:      map-get($breakpoints, small),
        max:        map-get($breakpoints, small) * 1.25,
        rootsize:   14px
    ),
    1: (
        start:      map-get($breakpoints, medium),
        max:        map-get($breakpoints, medium) * 1.25,
        rootsize:   16px
    ),
    2: (
        start:      map-get($breakpoints, large),
        max:        map-get($breakpoints, large) * 1.25,
        rootsize:   16px
    )
);
```

And that's about all we did; the MegaType `rootsize` you set dictates the global scale of all Foundation components proportionately, which works really well. So just set the rootsizes to your preferences, in this example I have a smaller type/grid scale for my mobile breakpoint (14px as opposed to 16px everywhere else). 

Note the `max` value is mostly arbitrary as the only thing it affects is the optional `set-container` mixin; we just manually tweaked this to fit our design.

On a related note we will soon be building a few demos to better demonstrate a few MegaType use cases / configs, and a demo Foundation 6 setup is planned.

Hopefully this helps with your use case; keen to hear any further issues you encounter when working with Foundation!

**Comment by glennphilp** [comment]
Hey @tbredin, is there a chance you could post to GitHub your Foundation 6 and MegaType test case?

**Comment by glennphilp** [comment]
Hey @tbredin, could you also provide some insight on using rem-calc() a Foundation function with MegaType or should users be using px-to-em() and px-to-rem()?

**Comment by tbredin** [comment]
@glennphilp You'll have more success with the MegaType function since it has an awareness of the `rootsize` that's tied to the breakpoint you're using, whereas Foundation assumes 16px as far as I know. 

Also; I've finally found some space in my schedule to spin up a foundation integration example, stay tuned

**Comment by tbredin** [comment]
Hey everyone, I've set up a demo for the way we're using MegaType with Foundation 6 currently. It's not complete yet (many components push lower elements off the grid), but this serves as a proof-of-concept for how well these integrate. We're using something _similar_ to this in production with a lot of success. 

https://github.com/StudioThick/megatype-foundation

[Demo](megatype-foundation.studiothick.com)

While I've fixed some of the stranger clashes (see the bottom of `_globals.scss`); I haven't massaged _every single_ individual Foundation component to suit MegaType's baseline, and some certainly need it. I encourage everyone to do so for the components you need!

Also note that this demo is intended as a proof of concept and we won't be doing a lot of Foundation-specific support unless it's clear that it's caused by a problem in the way MegaType itself works.
