### ISSUE TITLE
Possible to change "mobile-first" assumption?

### ISSUE THREAD

**Issue by eikaramba** [StudioThick/megatype#26]
It seems mobile-first is an assumption that is hardcoded into the framework. Because our breakpoints look like this

```
$breakpoint-map: (
        0: (
                start:          0,
                max:            map-get($breakpoints, sm),
                rootsize:       14px
        ),
        1: (
                start:          map-get($breakpoints, md),
                max:            map-get($breakpoints, lg),
                rootsize:       16px
        ),
        2: (
                start:          map-get($breakpoints, lg),
                max:            map-get($breakpoints, xl),
                rootsize:       16px
        ),
        3: (
                start:          map-get($breakpoints, xl),
                max:            map-get($breakpoints, xl) * 1.25,
                rootsize:       18px
        )
);
```

However we have a desktop "app" where we force mobile clients to use the native apps, thus our "base" css is defined for breakpoint 1 or 2 with a rootsize of 16px.

Now when i use megatype the first html declaration written by `@include megatype;` gives me

```
html {
  font-size: 87.5%;
}
```

**Question:** How can i change megatype, so that we don't need to declare mobile-first statements in css, but instead can use the media query mixins to specify statements explicitly for mobile, tablet, big desktops etc.?

**Comment by tbredin** [comment]
Yep, I think you're correct that we've made that assumption in some places. Ideally it would only do so if the breakpoint map starts with `0`. 
Just to make sure I'm following your requirements, can you confirm that what you're looking for is essentially:
- The ability to declare exclusionary media queries, ie; `min-width` **and** `max-width` so that the style applies only to a specific range? (IIRC this exists, but we could certainly have a look at documenting this better)
- HTML `font-size` default to be output from a configurable breakpoint rather than assumed as the first breakpoint (I'm struggling to wrap my head around how this would work — how we could build it and make it usable and intuitive — to be honest)

The media query setup already on our radar as a candidate for a bit of a cleanup, we might see what we can tease out of this discussion as some actions as a part of that.

**Comment by eikaramba** [comment]
Thanks for your quick reply! :)

I don't think i'm necessarly looking for min-width and max-width media queries, but yes the default font-size of the html selector should be not just taken from the first breakpoint but instead from one, the developer can choose. Also then the media queries automatically generated for the HTML Tag by `@include megatype` should not exclude the first one, but instead the one that was choosen.

Just imagine you want to write your CSS for a desktop webpage(~1000px width) and now also want to be able to selectively say "make this smaller on mobile" or "make this bigger on high-resolution screens".

Maybe you can point me into the right direction, as this might not be needed to be dynamically configured if it is too complex. I'm happy to fork the project and make the necessary changes for our use case. I already saw that in the `_typography.scss`one needs to change

```
50: $min-size: nth($sizes, 1); //Use specified breakpoints as index here not fixed values
```

and

```
60: @for $i from 2 through $breakpoint-count //don't start from 2, but instead just skip the "default" breakpoint index
```

**Comment by eikaramba** [comment]
Okay so far so good i forked the project and made my changes. THOSE ARE NOT YET PRODUCTION READY. I deleted some code and made a lot of changes just for our use case. However there are ideas, that might be useful for the future in general
https://github.com/eikaramba/megatype/commit/778535b8452832f978f9e0f62b192acf39fc7eb0
- Change breakpoints to use string literals like "sm", "lg" etc.
- Change media and breakpoint-layout methods to use "-1" as defaults(made more sense when breakpoints where still numbers) so that
  - (-1,lg) => max-screen
  - (lg, -1) => min-screen
  - (sm,lg) => min-screen and max-screen
- Fixed some problems where somehow rem and em values or so were mixed and... well SASS doesn't liked that ;)

For completness here some code examples:

```
$breakpoint-map: (
        sm: (
                start:          0em,
                max:            map-get($breakpoints, sm),
                rootsize:       14px
        ),
        md: (
                start:          map-get($breakpoints, sm),
                max:            map-get($breakpoints, md),
                rootsize:       16px
        ),
        lg: (
                start:          map-get($breakpoints, md),
                max:            map-get($breakpoints, lg),
                rootsize:       16px
        ),
        xl: (
                start:          map-get($breakpoints, lg),
                max:            map-get($breakpoints, xl),
                rootsize:       16px
        ),
        xxl: (
                start:          map-get($breakpoints, xl),
                max:            map-get($breakpoints, xxl),
                rootsize:       18px
        )
);
$current-breakpoint: xl !default;
$current-rootsize: map-get(map-get($breakpoint-map, xl), rootsize) !default;
```

```
.example {
    @include typeset($sans, font-size(0), line-height(0), 1, 1);

        @include min-width(lg) {
            @include typeset($sans, font-size(1), line-height(1), 1, 1);
        }
        @include max-width(sm) {
            @include typeset($sans, font-size(-1), line-height(-1), 1, 1);
        }
}
```

For now i removed the html setup because it was easier to just manually write:

```
@media (max-width: 35.5em) {
    html {
        font-size: 87.5%;
    }
}

@media (min-width: 90em) {
    html {
        font-size: 112.5%;
    }
}
```

BTW the font-size function is basically inspired by https://scotch.io/tutorials/aesthetic-sass-3-typography-and-vertical-rhythm, i like it to use modular scale.

Disclaimer: I'm still not certain that everything i did is really like i should do it, also i still have problems sometimes to understand when to use rem and my computed-base-line(let's call it `$vr`) in css?? E.g. in your test project you also declare a `base-font * base-line-height` variable and say this can be used for margins, paddings etc. But in my test this was not working so good because the grid is always layouted as 1rem. My `$vr` variable however is 1.5rem. The grid persisted only when i was using multiples of 1rem. So `2*$vr` is working but `1*$vr` not :(

Anyway, hopefully i find the time to improve my fork and maybe at some point certain changes can be adapted back to the main project :)

**Comment by tbredin** [comment]
> Just imagine you want to write your CSS for a desktop webpage(~1000px width) and now also want to be able to selectively say "make this smaller on mobile" or "make this bigger on high-resolution screens".

I think this is a valid use case we'd like to support, thanks for that fork, that's awesome and highlights a few issues for us, but I'm not sure we're quite there yet.  
Few points
- I'm very very conscious that we keep the design of this system as easy to use as possible. This means we should be very careful not to introduce too much complexity for edge-cases if it makes life for the average user much more complex. It's a balancing act.
- We'll probably hang on to the `@include megatype` declaration that specs this out from the config automatically. Open to supporting more configurable output for this however.
- Not really on board with using keywords for breakpoints. This is perhaps a more opinionated part of the project; we think numbered breakpoints are more elegant, require less work when adding/inserting new breakpoints (starts to get weird when you start throwing in `xxl` or `xxsm` etc), especially when considering overhead required to use these in math and build functions / mixins around as well. We think these make more sense than `md`, `lg`, etc, which may not correspond well to what any given dev considers to be "medium" or "large", and most often boils down to a learned linear sequence (numbers being the simplified pattern there).
- We've got a design vision for tidying up the breakpoint mixin setup (TLDR; `breakpoint-layout` will be combined with `media` and depreciated). The working titles we have for these mixins are pretty self-explanatory: `media` (main, 2-parameter mixin that does all the work, absorbing `breakpoint-layout`), and then `min-width` and `max-width` (Just 1-parameter shortcut wrapper mixins for `media`). We want these to be capable of accepting a space separated `list` of `px`, `em`, or breakpoint keys (which will still be unitless numbers).
- I suspect your `$vr` is getting rounded because you have `baseline-snap: true`, maybe? This rounds baseline units to the nearest full `1rem`, which off the top of my head I think would affect that.

I'm pretty busy over the next few weeks but I am now actively trying to clear some time to address this and some other issues soon.

**Comment by tbredin** [comment]
I have added a variable to allow customisation of rootsize output. 

```
// _config.scss
// default breakpoint. This is where the default html font size will be set,
// media queries will be generated to either side to apply rootsizes at remaining breakpoints
// eg: for mobile first set this to 0, for desktop first set this to your largest breakpoint (with this config, 4)
$default-break: 0 !default;
```

This will output the html font sizes in a style similar to the media queries you have mentioned above, which will allow you to develop at any default width and then define overrides in either direction later.

From here's it's easy to use the `min-width` & `max-width` mixins to target breakpoints from the config, or use `media` directly to target a min & max width breakpoint range, eg:

```
// default style here 

@include min-width(3) {
  // above breakpoint 3
}

@include max-width(2) {
  // below breakpoint 2
}

@include media(1, 2) {
  // between breakpoint 1 and breakpoint 2
}
```

See de58dfe78a40407d03cf4f865f386aa40912ea57

Caveat: we have no intention of supporting this for the slightly more novel `baseline-scaling` mode (we haven't yet found a use for this in production).
