### ISSUE TITLE
Images inline and block

### ISSUE THREAD

**Issue by glennphilp** [StudioThick/megatype#34]
Could you provide some tips or examples on the best way to implement images (inline and block) within a typographic design? Working with megatype I have found images as-well-as a few other elements to give me fits. It would even be awesome to get something like [responsive aspect-ratios mixin](http://codepen.io/jakob-e/pen/WvrJwN) to work within megatype.

Screenshot with images:
![screen shot 2016-10-11 at 9 32 23 am](https://cloud.githubusercontent.com/assets/2106652/19275679/fff9879a-8f99-11e6-9ee0-59e788fd7950.png)

Screenshot without images:
![screen shot 2016-10-11 at 9 31 22 am](https://cloud.githubusercontent.com/assets/2106652/19275680/0006b906-8f9a-11e6-9e4a-2b94802f1763.png)

Any insight and examples would be greatly appreciated, though.

**Comment by tbredin** [comment]
I've usually been letting images interrupt the baseline grid, and let it resume (albeit sometimes with an offset) after the image. I see no reason a responsive aspect ratio mixin wouldn't work in this case (I use a very similar custom one). 

Key "gotcha" is that your images will need to be a height that is a multiple of the baseline unit (usually `1rem`) in order to maintain the baseline rhythm.

However if what you're looking for is something that can incrementally increase the size of a box to snap to round units of baseline, that's outside the scope of this project, and you're probably going to want to use javascript to watch for changes and round the height to the nearest baseline unit.
