### ISSUE TITLE
font-family property not used in typeset mixin

### ISSUE THREAD

**Issue by bbellx** [StudioThick/megatype#8]
Hi there!

I've been digging into MegaType and noticed that the `font-family` property of the font maps as defined in the `_config.scss` file (see below):

`$sans: (
    font-family: '"Helvetica Neue", Arial, sans-serif',
    regular: normal,
    bold: bold,
    cap-height: 0.71
);`

are never utilized in the `typeset()` mixin to actually set the `font-family` property on the selector.

I believe this can be resolved by adding the following lines to the `typeset()` mixin in the `_typography.scss` file:

`font-family: font-family-fallback-of($font);`
`font-family: font-family-of($font);`

I'm happy to make a pull request if you agree that this was an oversight. However, if I'm not utilizing the mixin appropriately, could you help me understand what I'm missing?

**Comment by bbellx** [comment]
Adding some conditional checks would be a good idea as well:

```
@if map-get($font, font-family-fallback) != null {
    font-family: font-family-fallback-of($font);
}

@if map-get($font, font-family) != null {
    font-family: font-family-of($font);
}
```

**Comment by tbredin** [comment]
Hi bbelix,

Although this might seem counterintuitive at first, for optimisation reasons it's not intended that the typeset mixin would directly output the `font-family` property. When you consider that the typeset mixin is intended for use at subsequent breakpoints, it makes sense not to repeat the output of this property. For example, consider the following:

```
@include typeset($sans, 14px, 1, 0, 1);
font-family: font-family-of($sans);

@include min-width(1) {
    @include typeset($sans, 16px, 1, 0, 2);
}

@include min-width(2) {
    @include typeset($sans, 18px, 1, 0, 2);
}
```

In this example, the `font-family` property currently only gets output where we declare it explicitly. If we were to output it with the typeset mixin, it would be output 3 times, and the latter 2 would be redundant.

However we do need to still feed in the font variable to this mixin so that we can retrieve it's stored `cap-height` for use in rhythm math.
